spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/lesson2
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true